# Generated by Django 5.2.7 on 2025-11-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='editors',
        ),
    ]
